package es.us.master;
// Generated 05-ago-2015 15:09:36 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", schema = "C##ALEMARCHA")
public class Usuario implements java.io.Serializable {

	private BigDecimal id;
	private String nombre;
	private String password;

	public Usuario() {
	}

	public Usuario(BigDecimal id, String nombre, String password) {
		this.id = id;
		this.nombre = nombre;
		this.password = password;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "PASSWORD", nullable = false, length = 120)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
