package es.us.master;
// Generated 03-jul-2015 20:05:13 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", schema = "C##ALEMARCHA")
public class Usuario implements java.io.Serializable {

	private BigDecimal id;
	private String nombre;

	public Usuario() {
	}

	public Usuario(BigDecimal id) {
		this.id = id;
	}

	public Usuario(BigDecimal id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
